version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "disco-browser"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-xhgv0fjfsqig"
s3_prefix = "disco-browser"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
