version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "disco-browser"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-xhgv0fjfsqig"
s3_prefix = "disco-browser"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "LambdaSg=\"sg-e16da6d1\" LambdaSubnets=\"subnet-d40a9989,subnet-19ba3a61,subnet-d68f84fd,subnet-62d67b28\" DBName=\"dancedb\""
