AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  browser

  Sample SAM Template for browser


Parameters:
  LambdaSg:
    Description: "Lambda security group ID"
    Type: AWS::EC2::SecurityGroup::Id
  LambdaSubnets:
    Description: "Lambda subnets"
    Type: List<AWS::EC2::Subnet::Id>
  DBName:
    Description: Database name
    Type: String
    MinLength: '1'
    MaxLength: '30'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBUsername:
    NoEcho: 'true'
    Description: Username for MySQL database access
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBPassword:
    NoEcho: 'true'
    Description: Password MySQL database access
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.


    # More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    CodeUri: disco_base/
    Runtime: python3.8
    Environment:
      Variables:
        DBNAME: !Ref DBName
        DBUSERNAME: !Ref DBUsername
        DBPASSWORD: !Ref DBPassword
        DBCONNECTION: !GetAtt DanceDatabaseCluster.Endpoint.Address
    VpcConfig:
      SecurityGroupIds:
        - !Ref LambdaSg
      SubnetIds: !Ref LambdaSubnets

Resources:
  DanceDatabaseCluster:
    Type: 'AWS::RDS::DBCluster'
    Properties:
      DatabaseName: !Ref DBName
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBClusterIdentifier: disco-db
      Engine: aurora
      EngineVersion: 5.6.10a
      EngineMode: serverless
      EnableHttpEndpoint: true
      ScalingConfiguration:
        AutoPause: true
        MinCapacity: 4
        MaxCapacity: 32
        SecondsUntilAutoPause: 1000


  DiscoApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: Disco Api Gateway
      StageName: Prod
      Cors:
        AllowMethods: "'POST, GET'"
        AllowOrigin: "'*'"
        MaxAge: "'600'"


  HomePageFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: page-home
      Handler: server_app.homepage
      Policies:
        - VPCAccessPolicy: {}
        - S3FullAccessPolicy:
            BucketName: "*"
      Events:
        HomePage:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref DiscoApiGateway
            Path: /
            Method: get


  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: test-hello-world
      Handler: server_app.hello_world
      Policies:
        - VPCAccessPolicy: {}
        - S3FullAccessPolicy:
            BucketName: "*"
      Events:
        HelloWorld:
          Type: Api 
          Properties:
            RestApiId: !Ref DiscoApiGateway
            Path: /hello_world
            Method: get

  ShowVideoFunction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: video-show
      Handler: server_app.show_video
      Policies:
        - VPCAccessPolicy: {}
        - S3FullAccessPolicy:
            BucketName: "*"
      Events:
        ShowVideo:
          Type: Api 
          Properties:
            RestApiId: !Ref DiscoApiGateway
            Path: /video/{id}
            Method: get

  ListDancesFunction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: dance-list
      Handler: server_app.list_dances
      Policies:
        - VPCAccessPolicy: {}
        - S3FullAccessPolicy:
            BucketName: "*"
      Events:
        ListDances:
          Type: Api 
          Properties:
            RestApiId: !Ref DiscoApiGateway
            Path: /dance
            Method: get

  GetDanceFunction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: dance-get
      Handler: server_app.get_dance
      Policies:
        - VPCAccessPolicy: {}
      Events:
        ShowVideo:
          Type: Api 
          Properties:
            RestApiId: !Ref DiscoApiGateway
            Path: /dance/{id}
            Method: get

  CreateDanceFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: dance-create
      Handler: server_app.create_dance
      Policies:
        - VPCAccessPolicy: {}
        - S3FullAccessPolicy:
            BucketName: "*"
      Events:
        CreateDance:
          Type: Api 
          Properties:
            RestApiId: !Ref DiscoApiGateway
            Path: /dance
            Method: post

  UpdateDanceFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: dance-update
      Handler: server_app.update_dance
      Policies:
        - VPCAccessPolicy: {}
        - S3FullAccessPolicy:
            BucketName: "*"
      Events:
        CreateDance:
          Type: Api
          Properties:
            RestApiId: !Ref DiscoApiGateway
            Path: /dance/{id}
            Method: put

  DeleteDanceFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: dance-delete
      Handler: server_app.delete_dance
      Policies:
        - VPCAccessPolicy: {}
        - S3FullAccessPolicy:
            BucketName: "*"
      Events:
        CreateDance:
          Type: Api
          Properties:
            RestApiId: !Ref DiscoApiGateway
            Path: /dance/{id}
            Method: delete   

  InitDBFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: db-reset
      Handler: server_app.init_db
      Policies:
        - VPCAccessPolicy: {}
        - S3FullAccessPolicy:
            BucketName: "*"
      Environment:
        Variables:
          DBNAME: !Ref DBName
          DBUSERNAME: !Ref DBUsername
          DBPASSWORD: !Ref DBPassword
          DBCONNECTION: !GetAtt DanceDatabaseCluster.Endpoint.Address
            
 
          


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HomePageApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${DiscoApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  HomePageFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HomePageFunction.Arn
  HomePageFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HomePageFunctionRole.Arn
