AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  browser

  Sample SAM Template for browser

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  DiscoApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: Disco Api Gateway
      StageName: Prod
      Cors:
        AllowMethods: "'POST, GET'"
        AllowOrigin: "'*'"
        MaxAge: "'600'"


  HomePageFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: disco_base/
      Handler: server_app.homepage
      Runtime: python3.8
      Events:
        HomePage:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref DiscoApiGateway
            Path: /
            Method: get

  ShowVideoFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: disco_base/
      FunctionName: show-video
      Handler: server_app.show_video
      Runtime: python3.8
      Events:
        ShowVideo:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref DiscoApiGateway
            Path: /video/{id}
            Method: get

  ListVideosFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: disco_base/
      Handler: server_app.list_videos
      Runtime: python3.8
      Events:
        HomePage:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref DiscoApiGateway
            Path: /video
            Method: get

            
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HomePageApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${DiscoApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  HomePageFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HomePageFunction.Arn
  HomePageFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HomePageFunctionRole.Arn
